ZSH_CONFIG_DIR="$HOME/.zsh/"

# Load prompt
source $ZSH_CONFIG_DIR/prompt.zsh

# Load z
# Quickly jump around directories based on frequencie
source $ZSH_CONFIG_DIR/packages/z/z.sh

# Setup NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# Load key bindings and completion from fzf
# Fail silently if they do not exist
source /usr/share/fzf/key-bindings.zsh &> /dev/null
source /usr/share/fzf/completion.zsh &> /dev/null

# Load all my functions
for file in $ZSH_CONFIG_DIR/functions/*.zsh; do
  source $file
done
