ZSH_CONFIG_DIR="$HOME/.zsh/"

# Load prompt
source $ZSH_CONFIG_DIR/prompt.zsh

# Load aliases
source $ZSH_CONFIG_DIR/aliases.zsh

# Load z
# Quickly jump around directories based on frequencie
source $ZSH_CONFIG_DIR/packages/z/z.sh

# Setup NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# Load key bindings and completion from fzf
# Fail silently if they do not exist
source /usr/share/fzf/key-bindings.zsh &> /dev/null
source /usr/share/fzf/completion.zsh &> /dev/null

# Load all my functions
for file in $ZSH_CONFIG_DIR/functions/*.zsh; do
  source $file
done

# Setup fish shell like autocomplete
# MUST be the last thing in the config file, see
# https://github.com/zsh-users/zsh-syntax-highlighting#why-must-zsh-syntax-highlightingzsh-be-sourced-at-the-end-of-the-zshrc-file
source $ZSH_CONFIG_DIR/packages/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZSH_CONFIG_DIR/packages/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
