#!/bin/bash

# Start sxhkd for key board shortcuts
SXHKD_SHELL=bash sxhkd &

# Start the status bars on all enabled moniters
killall polybar
readarray -t MONITORS < <(xrandr | grep -Eo "^\S+ connected" | cut -d " " -f 1)
for MONITOR in "${MONITORS[@]}"
do
    MONITOR=$MONITOR polybar top &
    MONITOR=$MONITOR polybar bottom &
done

bspc config border_width 2 # Make the borders look nice
bspc config window_gap 2 # Make the window gaps just right

# Setup mouse
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action1 resize_corner

# Default settings, not sure what they all do
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# Add some desktops
for MONITOR in "${MONITORS[@]}"
do
    bspc monitor $MONITOR  -d 1 2 3 4 5 6 7 8 9
done

# Add some rules for specific programs
bspc rule -a Emacs state=tiled
