#!/bin/bash

# Start sxhkd for key board shortcuts
SXHKD_SHELL=bash sxhkd &
./.screenlayout/makawao-dual-right.sh

# Start the status bars on all enabled moniters
killall polybar
MONITORS=$(xrandr | grep -Eo "^\S+ connected" | cut -d " " -f 1)
for MONITOR in $MONITORS
do
    MONITOR=$MONITOR polybar top &
    MONITOR=$MONITOR polybar bottom &
done

bspc config border_width 2 # Make the borders look nice
bspc config window_gap 2 # Make the window gaps just right

# Default settings, not sure what they all do
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# Add some desktops
bspc monitor -d I II III IV V VI VII VIII IX X

# Add some rules for specific programs
bspc rule -a Emacs state=tiled
