#!/bin/bash

# Start sxhkd for key board shortcuts
SXHKD_SHELL=bash sxhkd &

# Start the status bars on all enabled moniters
killall polybar # Kill any existing bars

# Read a list of the active monitors
readarray -t MONITORS < <(xrandr | grep -Eo "^\S+ connected" | cut -d " " -f 1)

## Start the bars on the primary monitor
MONITOR="${MONITORS[0]}" polybar top-primary &
MONITOR="${MONITORS[0]}" polybar bottom-primary &

# Start the secondary bars on all the other monitors
for MONITOR in "${MONITORS[@]:1}"
do
    MONITOR=$MONITOR polybar top-secondary &
    MONITOR=$MONITOR polybar bottom-secondary &
done

bspc config border_width 2 # Make the borders look nice
bspc config window_gap 2 # Make the window gaps just right

# Setup mouse
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action1 resize_corner

# Default settings, not sure what they all do
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# Add some desktops
for MONITOR in "${MONITORS[@]}"
do
    bspc monitor $MONITOR  -d 1 2 3 4 5 6 7 8 9
done

# Add some rules for specific programs
bspc rule -a Emacs state=tiled
