"""" Vundle Setup """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set nocompatible    " be iMproved, required
filetype off        " required

" Set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

"""" Here be the plugins """"""""""""""""""""""""""""""""""""""""""""""""""""""
Plugin 'gmarik/Vundle.vim'
Plugin 'sickill/vim-monokai'
Plugin 'mattn/emmet-vim'
Plugin 'scrooloose/syntastic'
Plugin 'airblade/vim-gitgutter'
Plugin 'digitaltoad/vim-jade'
Plugin 'bling/vim-airline'
Plugin 'moll/vim-bbye'
Plugin 'Shougo/vimproc.vim'
Plugin 'Shougo/unite.vim'
Plugin 'kchmck/vim-coffee-script'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-surround'
Plugin 'Valloric/YouCompleteMe'
Plugin 'marijnh/tern_for_vim'
Plugin 'tpope/vim-eunuch'
Plugin 'tpope/vim-fugitive'
Plugin 'dag/vim-fish'
Plugin 'sirver/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'rhysd/clever-f.vim'
Plugin 'xolox/vim-misc'
Plugin 'xolox/vim-session'
Plugin 'valloric/MatchTagAlways'
Plugin 'majutsushi/tagbar'
Plugin 'fatih/vim-go'
Plugin 'groenewege/vim-less'
Plugin 'Glench/Vim-Jinja2-Syntax'
Plugin 'leafgarland/typescript-vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'wavded/vim-stylus'
Plugin 'cespare/vim-toml'
Plugin 'lambdatoast/elm.vim'

"""" Vundle Teardown """"""""""""""""""""""""""""""""""""""""""""""""""""""""""
call vundle#end()   " required

"""" Vanilla Configs """"""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Turn on syntax and filetype detection
syntax on
filetype plugin indent on

" Use bash as the shell
set shell=/bin/bash

" Set location for backup and swap files
set backupdir=~/.vim/.backup//
set directory=~/.vim/.swap//

" Show line numbers
set number

" Don't show the mode in the status line
set noshowmode

" Setup tabs
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab       " Use spaces instead of tabs
set smarttab        " Let's tab key insert 'tab stops', and bksp deletes tabs
set shiftround      " Tab/shifting moves to closest tabstop
set autoindent      " Match indents on new lines
set smartindent     " InPlugin 'sickill/vim-monokai'tellegently dedent/indent new lines based on rules

" Autoreload changed files without asking
set autoread

" Sane backspace
set backspace=indent,eol,start

" Make search better
set ignorecase  " Case insensitive search
set smartcase   " If there are uppercase letters, become case-sensitive
set incsearch   " Live incremental searching
set showmatch   " Live match highlighting
set hlsearch    " Highlight matches
set gdefault    " Use the `g` flag by default

" Set Leader Key
let mapleader = "\<Space>"

" Bind ';' to ':' so we don't have to press shift to input a command
nnoremap ; :
vnoremap ; :

" Bind jj to esc to exit insert mode faster
inoremap jj <esc>

" Change shortcuts for copy, cut and paste
vmap <C-c> "+yi
vmap <C-x> "+c
vmap <C-v> c<ESC>"+p
imap <C-v> <C-r><C-o>+

" Allow hidden buffers without and error
set hidden

" Stop auto-comment
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" Disable Arrow
map <Up> <NOP>
map <Down> <NOP>
map <Left> <P>
map <Right> <P>
imap <up> <nop>
imap <down> <nop>
imap <left> <nop>
imap <right> <nop>

" Swap lines up and down
nnoremap <C-j> :m .+1<CR>==
nnoremap <C-k> :m .-2<CR>==
inoremap <C-j> <Esc>:m .+1<CR>==gi
inoremap <C-k> <Esc>:m .-2<CR>==gi
vnoremap <C-j> :m '>+1<CR>gv=gv
vnoremap <C-k> :m '<-2<CR>gv=gv

" Allow the cursor to go to the end of the line
set virtualedit=onemore

" Minimal ui
set guioptions=ae

" Hide the tabline
set showtabline=0

" Use the mouse in the terminal
set mouse=a

" Leader+w saves all buffers
noremap <Leader>w :wa!<CR>

" Close the scratch buffer after I finish the completion or exit insert mode
autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
autocmd InsertLeave * if pumvisible() == 0|pclose|endif

" Toggle between current and previously edited file
map <leader><Backspace> <C-^>

" Highlight .ejs files with html
au BufNewFile,BufRead *.ejs set filetype=html

" Exit insert mode with Control-c
imap <C-c> <ESC>

""""" Plugin Configs """""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" Gitgutter
" Always show the gitgutter sign column
let g:gitgutter_sign_column_always = 1

"" Airline
" Enable it
let g:airline#extensions#tabline#enabled = 1
set laststatus=2

if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif

" Get rid of the ugly arrows
let g:airline_left_sep=''
let g:airline_right_sep=''
let g:airline_left_alt_sep=''
let g:airline_right_alt_sep=''

"" bbye
nnoremap <Leader>q :Bdelete<CR>

"" Unite
" File search
nnoremap <C-p> :Unite -start-insert file_rec/async<cr>

" Content search
nnoremap <Leader>/ :Unite grep:.<cr>

" Quick buffer and tab switching
nnoremap <Leader>s :Unite -start-insert tab<cr>
nnoremap <Leader>a :Unite -start-insert buffer<cr>

" Use ag for searching(to follow .gitignores)
let g:unite_source_rec_async_command='ag --nocolor --nogroup --ignore ".git" --hidden -g ""'

"" Commentary
" Toggle comments
vmap <Leader>c gc
nmap <Leader>c gcc

"" UtilSnips
let g:UltiSnipsExpandTrigger="<right>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

"" Vim-Session
" Auto save on exit
let g:session_autosave = 1

" Auto save session every once and awile
let g:session_autosave_periodic = 5 " Minutes

"" Vim-go
" Quick go commands
au FileType go nmap <leader>r <Plug>(go-run)
au FileType go nmap <leader>b <Plug>(go-build)
au FileType go nmap <leader>t <Plug>(go-test)
au FileType go nmap <leader>c <Plug>(go-coverage)

" Go to declaration
au FileType go nmap gd <Plug>(go-def)
au FileType go nmap <Leader>ds <Plug>(go-def-split)
au FileType go nmap <Leader>dv <Plug>(go-def-vertical)
au FileType go nmap <Leader>dt <Plug>(go-def-tab)

" Open up godoc
au FileType go nmap <Leader>g :Godoc<cr>

" Use goimports
let g:go_bin_path = expand("~/Projects/go/bin")
let g:go_fmt_command = "goimports"

" Go + TagBar
nmap <F8> :TagbarToggle<CR>
let g:tagbar_type_go = {
    \ 'ctagstype' : 'go',
    \ 'kinds'     : [
        \ 'p:package',
        \ 'i:imports:1',
        \ 'c:constants',
        \ 'v:variables',
        \ 't:types',
        \ 'n:interfaces',
        \ 'w:fields',
        \ 'e:embedded',
        \ 'm:methods',
        \ 'r:constructor',
        \ 'f:functions'
    \ ],
    \ 'sro' : '.',
    \ 'kind2scope' : {
        \ 't' : 'ctype',
        \ 'n' : 'ntype'
    \ },
    \ 'scope2kind' : {
        \ 'ctype' : 't',
        \ 'ntype' : 'n'
    \ },
    \ 'ctagsbin'  : 'gotags',
    \ 'ctagsargs' : '-sort -silent'
\ }

""""" Color Scheme """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" Set our colorscheme to solorized dark
set background=dark
colorscheme solarized

"" Fix gitgutter's colors
highlight! link SignColumn LineNr

